### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by charlie-j** [EasyCrypt/solveq#2]
Parser pour:
 monoide -> cste, oper, exp
 bitstrings -> +,*,0_n, 1_n

**Comment by strub** [comment]
Don't we have a more detailed file regarding the syntax somewhere? I do remember that we wrote more stuffs on the blackboard.

**Comment by charlie-j** [comment]
Alors, ce qu'on veut en première instance c'est:

Terms:
```
Bitstrings := x+y, x*y, 0_n, 1_n
Corps Finis := 0,1, x+y,x*y
Monoide := g, g^x , g1 * g_2
Variables := x,y,z,.... 
Abstract functions symbols := f(x,y,z)
```
Potentiellement, les symboles de fonctions abstraits peuvent convertir les types. 

Après, on veut pouvoir appeller des fonctions sur nos termes, du genre calculer l'inverse d'un terme vis à vis d'un ensemble précis de variable, un appel qui ressemblerait à :
`get_inverter term (variables set)`
