### ISSUE TITLE
Déduction monoidale

### ISSUE THREAD

**Issue by charlie-j** [EasyCrypt/solveq#3]
Implémenter la déduction dans les monoides.
   -> Biblio 
  -> implem

**Comment by charlie-j** [comment]
Biblio : https://members.loria.fr/VCortier/files/Papers/LPAR07.pdf

C'est un peu plus complexe que ce que j'avais imaginé, il faut résoudre des systèmes d'équations linéaires à la fin. À voir si on veut pas juste une heuristique plutôt.

**Comment by strub** [comment]
La dernière partie ne me fait pas trop peur, j'ai ce qu'il faut quelque part en principe. Par contre, j'ai du mal à comprendre où est la transformation d'un problème de décision dans une théorie équationnelle monoïdale vers un système d'eqs linéaire.

**Comment by charlie-j** [comment]
Le théorène qui nous intéresse est le Thm 1, c'est là qu'ils réduisent la déduction à un problème d'algèbre linéaire. La preuve du thm est pas juste après, mais commence en bas de la page.

Le reste du papier nous intéresse pas, c'est pour l'équivalence statique après.
